- bottle.py
Here's another one dependant on #690
The regexes claimed to match "start of line" when in fact, they did not.By using `.search(s, pos=p)` over `.search(s[p:])`, this now works correctly. This allows the special casing of ternary if to be removed.
The previous regex would allow `% if True: foo() end`, the new one requires `% if True: foo(); end`, which seems to be what the old regex intended anyway.
> Stpl less slicing

- README.rst
The link to the Google App Engine at code.google.com no longer functions, so it has been updated to point to the current Google App Engine PaaS site.
> Updated link to Google App Engine in Readme.rst

- docs/recipes.rst
This one is using a `before_request` hook to strip the trailing slash from `request.environ['PATH_INFO']`. I prefer it to the WSGI middleware method because it leaves the API of the app intact. For example, in the `StripPathMiddleware` snippet, you can't later add a route to `myapp` because you'll get the following error: `AttributeError: 'StripPathMiddleware' object has no attribute 'route'`.
> Added another recipe for removing trailing slashes

- bottle.py
Currently, Bottle imports the subprocess module always, even though it's only used with the auto-reloader behavior. This change only imports the module when it will be used.
I'm using Bottle via an embedded Python interpreter in a not-entirely-Python application. Importing the subprocess module causes the embedded Python to try to handle signals. I want all signal handling done in the embedding application, and auto-reload doesn't work for embedding anyway, so I don't want to load subprocess.
> only import subprocess if it's needed

- bottle.py
- test/test_route.py
Continuation of #739.
I've cleaned the code and added working test example of conditions, which triggers the bug. The bug is probably caused by inspect module being confused by modification of ``kwargs``. Here is example from tests, which can trigger the bug:
```python
def test_callback_inspection_multiple_args(self):
def d2(f="1"):
def d(fn):
def w(*args, **kwargs):
kwargs["a"] = f
return fn(*args, **kwargs)
return w
return d
@d2(f='foo')
def x(a, b):
return
route = bottle.Route(None, None, None, x)
self.assertEqual(set(route.get_callback_args()), set(['a', 'b']))
```
The bugfix just goes over all parameters and looks for one which looks like function. That is different from current code, which just takes first parameter and hopes, that it is function.
> .get_undecorated_callback() bugfix

- bottle.py
I couldn't find the case, where func is ``None``.
See #740 for details.
> Removed unnecessary `and func is not None` check.

- docs/deployment.rst
The current example of apache virtual server does not work with Apache 2.4. I added an example that works with that version.
> Newer versions of apache use a slightly different configuration

- .travis.yml
- test/test_environ.py
This is a solution for #791.
A few tests are failing because of [some recent changes](http://bugs.python.org/issue23250) in `http.cookies`:
- `test_set_cookie_secure`
- `test_set_cookie_httponly`
`test_delete_cookie` fails too, I'm not entirely sure why. The workaround is to check for containment of `'Max-Age=-1'`.
Also, I added Python 3.5 to `.travis.yml`.
> Fix cookie tests in test_environ.TestResponse

- bottle.py
[`inspect.getargspec`](https://docs.python.org/3/library/inspect.html#inspect.getargspec) has been removed
> Deprecated since version 3.0: Use signature() and Signature Object, which provide a better introspecting API for callables. This function will be removed in Python 3.6.
bottle.py fails with the following error:
```
Traceback (most recent call last):
File "<file>", line 77, in <module>
from inspect import getargspec
ImportError: cannot import name 'getargspec'
```
> cannot import name 'getargspec' in Python 3.6(-dev)

- bottle.py
A followup to #794.
From the documentation:
> defaults is a tuple of default argument values or None if there are no default arguments
so `return (args, varargs, keywords, tuple(defaults) or defaults)` should be `return (args, varargs, keywords, tuple(defaults) or None)`.
Sorry for this.
> Fix minor error in getargspec

- bottle.py
JSON requests should not return a 500 error as the issue is with
the requester's json and not the server itself. Fixes #654
> Return 400 with bad json request

- bottle.py
Catching redirect exception which is raised in before_request hook. 
This an attempt to fix issue #815
> Catching redirect exception which is raised in before_request hook

- bottle.py
In short: `@view('some_template', template_lookup='./app/my_vews')` won't work
I want to add a lookup-path for templates in my app, so I hook `view` and add `temlate_lookup` to kwargs but it doesn't work.
``` python
from . import bottle
from .bottle import route, request, response
from . import config
view = functools.partial(bottle.view, template_lookup=[config.PATH + '/pages'])
```
This patch fix the problem by mixin args earlier.
> Mixin args into kwargs earlier in template()

- bottle.py
If `root` already ends in `os.sep`, don't add another one
This used to fail on windows, but somehow worked on unix
> Make `root='/'` work cross-platform

- bottle.py
Otherwise the custom syntax will not apply to "include"-d teamples
> Inherit template's syntax while rendering sub-templates

- README.rst
change badge links from https://pypip.in/ to https://img.shields.io/pypi/
> fix invalid badge links

- bottle.py
gevent.wsgi just backwards compatibility alias for gevent.pywsgi, `fast` option was useless.
see:
http://www.gevent.org/gevent.wsgi.html
https://github.com/gevent/gevent/commits/v1.1.1/gevent/wsgi.py
> remove deprecated logic from GeventServer

- AUTHORS
- Makefile
- README.rst
- bottle.py
HI Marcel, 
I removed some more old deprecated code which is no longer needed..
Also, this https://github.com/bottlepy/bottle/blob/master/bottle.py#L130
can also be removed, since all supported versions have this key word.
All https://hg.python.org/cpython/file/3.{2,3,4,5}/Lib/keyword.py have `as`.
Finally, can you give a hint when is Version to be released 0.13?
> More Python 2.6\3.0 clean up

- bottle.py
- test/test_environ.py
- test/test_server.py
All supported Python versions include the `as` keyword
https://hg.python.org/cpython/file/3.{2,3,4,5}/Lib/keyword.py.
> Remove workaround missing keyword `as`

- bottle.py
Previously, these would throw another error and obliterate the useful traceback, replacing it with a useless one
> Handle unprintable errors

- bottle.py
It seems that using `eval(compile(...))` throws away the name that we gave the `code` object. We don't use the return value of `eval` anyway, so `exec` is fine.
> Fix tracebacks that would contain <string> to contain the template path

- bottle.py
does not return the same results by making "raise" and "return"
```python
from bottle import run, get, HTTPResponse
@get('/test1')
def test1():
return HTTPResponse({'test': 'ko'}, 402)
@get('/test2')
def test2():
raise HTTPResponse({'test': 'ko2'}, 402)
run(host='0.0.0.0', port=9988)
```
bottle 0.12.9 results:
```
In [1]: import requests
In [2]: r = requests.get('http://localhost:9988/test1')
In [3]: r.text, r.headers['content-type']
Out[3]: ('{"test": "ko"}', 'application/json')
In [4]: r = requests.get('http://localhost:9988/test2')
In [5]: r.text, r.headers['content-type']
Out[5]: ('test', 'text/html; charset=UTF-8')
```
patch results:
```
In [1]: import requests
In [2]: r = requests.get('http://localhost:9988/test1')
In [3]: r.text, r.headers['content-type']
Out[3]: ('{"test": "ko"}', …
```
> raise HTTPResponse not working correctly

- README.rst
and update Python 3.x version, since CircleCI is now active ... You can show off with a badge.
> Add badge for CircleCI

- bottle.py
Some wsgi servers buffers `wsgi.errors` and error messages does not appear in logs. To fix that, after writing to `wsgi.errors` it should be flushed in order for content to be written to the file.
See: https://github.com/unbit/uwsgi/issues/1222
> Flush wsgi.errors

- docs/tutorial_app.rst
Flup webpage link was broken (outdated) in the tutorial.
> Fixed Flup webpage link

- bottle.py
Changed __hook_reversed into set.
Set literal is chosen (over list, tuple) because:
1. It is supported since python 2.7, which is the
lowest version of python supported by bottle
right now.
2. Set membership testing is fast.
3. Duplicates prevented.
> Fixed issue #911

- bottle.py
""" Register an output handler for a HTTP error code.
Can be used as a decorator or called directly ::
def error_handler_500(error):
return 'error_handler_500'
app.error(code=500, callback=error_handler_500)
@app.error(404)
def error_handler_404(error):
return 'error_handler_404'
"""
> make app.error can be used as a decorator or called directly.

- docs/tutorial_app.rst
Every sql connection is abbreviated to `conn` except for the very first `con`. Changed everything to `conn` for consistency.
> conn > con in tutorial app

- bottle.py
Running 2s test @ http://172.17.0.1:8080/
2 threads and 600 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   141.65ms  322.13ms   1.95s    90.33%
Req/Sec     6.73k     2.94k   11.84k    60.00%
26819 requests in 2.02s, 4.42MB read
Requests/sec:  **13257.19**
Transfer/sec:      2.19MB
Running 2s test @ http://172.17.0.1:8080/
2 threads and 600 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    55.01ms   95.84ms 888.11ms   92.93%
Req/Sec     5.95k     3.52k   13.20k    75.00%
23684 requests in 2.01s, 3.93MB read
Requests/sec:  **11762.51**
Transfer/sec:      1.95MB
code benchmark:
```python
from bottle import get, run
@get('/')
def bench():
return {'hello': 'world'}
run(host='0.0.0.0', port=8080, server='gunicorn', …
```
> Support ujson

- docs/recipes.rst
expect_errors=True not generate exception for "bad requests" ( status != 200)
I have checked /logout only with number
> Receiving a code other than 2xx generate exception

- docs/tutorial.rst
This affords at least some assurance that what you download is indeed Bottle.
> Update wget download instructions to use HTTPS for security

- bottle.py
- docs/tutorial.rst
As mentioned in #982, `set_cookie()` does not support  the "SameSite" cookie attribute.
This is because the `http.cookies` module doesn't support that either.
A reason for _this_ isn't really given. It's just that the module was based on RFC 2109 which "SameSite" is not a part of.
In the python repository changes have been made and a pull request opened (python/cpython#214) so that `http.cookies` could eventually support "SameSite" natively in 3.7.
However, since this is future stuff it doesn't really make a difference for bottle at the moment and i've come to the conclusion that it would be feature that's nice to have.
So i've added this feature to bottle, and updated the docs.
It doesn't to much, i just import the `_reserved` dict in which valid attributes for cookies are stored, …
> "SameSite" cookie feature (from issue #982)

- docs/tutorial_app.rst
missing GET method to strip edit and status
> Fix typo for todo tutorial line 300 and 301

- bottle.py
I think the `tob` fuction has a bug on this [line](https://github.com/bottlepy/bottle/blob/master/bottle.py#L164)
```Python
def tob(s, enc='utf8'):
if isinstance(s, unicode):
return s.encode(enc)
return bytes("" if s is None else s)
```
If pass `None` to `tob`, it will execute `bytes("")`. And there will be a `TypeError` that `string argument without an encoding`
I think you mean that `return b'' if s is None else bytes(s)`
> fix pass None to tob

- bottle.py
The error is raised when I try the following code in the interpreter:
```
>>> from bottle import ConfigDict
>>> c = ConfigDict()
>>> c.load_dict(1)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "bottle.py", line 2114, in load_dict
raise TypeError('Source is not a dict (r)' % type(key))
UnboundLocalError: local variable 'key' referenced before assignment
```
> Fix UnboundLocalError in the ConfigDict load_dict method

- test/test_app.py
- test/test_config.py
- test/test_environ.py
- test/test_html_helper.py
- test/test_jinja2.py
fix some deprecation warnings in tests(assertEquals -> assertEqual)
make tests test_environ and test_jinja2 runnable standalone as `python -m unittest test_environ.py`. All another tests have this ability.
> deprecation warnings; make tests runnable standalone

- bottle.py
This is a fix for #949 
Bug : With my configuration : (Python 3.6.5rc1 and latest bottle) I see this warning on every page display : 
[Fri Apr 06 10:58:52.502762 2018] [wsgi:error] [pid 17383:tid 140555989333760] [remote 10.0.2.2:40164] /opt/planisware/planibox/py/pb/ext/bottle.py:4088: DeprecationWarning: Flags not at the start of the expression '\\\\{\\\\{((?:(?mx)(      ' (truncated)
[Fri Apr 06 10:58:52.503202 2018] [wsgi:error] [pid 17383:tid 140555989333760] [remote 10.0.2.2:40164]   patterns = [re.compile(p % pattern_vars) for p in patterns]
Fix : I moved the flags in front of the regexp as requested by the Python documentation : https://docs.python.org/3/library/re.html#regular-expression-syntax 
Test : On my configuration, the warning has disappeared and all seems to still be …
> Add the flag in front of the regexp to avoid Deprecation warning

- .travis.yml
* Python 3.3 is went EOL last year  https://devguide.python.org/#branchstatus
* Python 3.7 is shipping  https://github.com/travis-ci/travis-ci/issues/9069
> Travis CI: remove Python 3.3 and add Python 2.7

- bottle.py
Should fix this
```
/.../bin/bottle.py:87: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import MutableMapping as DictMixin
```
> Fix Python 3.7 collections.abc DeprecationWarning

- bottle.py
Setting default value as -1 when "Content-Length" is empty. If not, currently it will raise a ValueError
> [bug] set default value for "Content-Length"

- bottle.py
Quick fix to ensure that the regex strings do not cause the bottle app to fail launch.  
Also ties in with the other parts of the constructed regex string parts where the back slashes are escaped.
> #1177 Bug fix of missing regex escaped back slashes

- docs/recipes.rst
Previously, the example yielded SyntaxError. Adding an equal sign
fixes the assertion syntax.
> Fix syntax in webtest login recipe

- docs/tutorial.rst
The documentation states, that redirect() raises an HTTPError exception.
But in the code it raises an HTTPResponse
```
def redirect(url, code=None):
""" Aborts execution and causes a 303 or 302 redirect, depending on
the HTTP protocol version. """
if not code:
code = 303 if request.get('SERVER_PROTOCOL') == "HTTP/1.1" else 302
res = response.copy(cls=HTTPResponse)
res.status = code
res.body = ""
res.set_header('Location', urljoin(request.url, url))
raise res
```
> Correcting documentation: redirect() raises HTTPResponse and not HTTPError

- docs/stpl.rst
> Updated documentation on SimpleTemplate and embedded blocks.

- .github/workflows/install-deps.sh
- .travis.yml
- bottle.py
- docs/_locale/_pot/deployment.pot
- docs/_locale/de_DE/LC_MESSAGES/deployment.po
- docs/_locale/pt_BR/LC_MESSAGES/_pot/deployment.po
- docs/_locale/pt_BR/LC_MESSAGES/deployment.po
- docs/_locale/ru_RU/LC_MESSAGES/deployment.po
- docs/_locale/zh_CN/LC_MESSAGES/_pot/deployment.po
- docs/_locale/zh_CN/LC_MESSAGES/deployment.po
- docs/deployment.rst
- test/servertest.py
- test/test_server.py
- test/travis_setup.sh
Ready for first round of review / discussion :smiley: 
Dropping rocket is for #1119 
aiohttp fixes are for #995
> [waiting for review] Complete backend testing

- bottle.py
Gunicorn configuration is now only pulled from what is supplied through Bottle, not (for example) re-parsed from the commandline. Follows Gunicorn's [documented approach for integrated applications](http://docs.gunicorn.org/en/stable/custom.html).
* Before: `./my-bottle-app.py -v` → launches gunicorn, which re-parses `sys.argv`, finds the `-v`, prints the gunicorn version, and quits. Likewise, any command line argument which wasn't valid for gunicorn would cause an `error: unrecognized arguments: --whatever` message.
* After: launches gunicorn
Requires gunicorn >19.0 (Jun 2014)
Fixes #756
> gunicorn: switch to use BaseApplication (fixes #756)

- docs/tutorial.rst
I tried testing this by building it with the bottlepy.org repository, but I wasn't able to get any link to work in the html files generated by that. This link is currently broken on the live page, though, because the capitalization doesn't match.
> Fix broken link to WSGI specification

- bottle.py
from standart module "operator"
```
def is_not(a, b):
"Same as a is not b."
return a is not b
```
> fix erroneous expression

- test/test_mount.py
It looks that #602 is gone, but I'm not sure when exactly it was fixed.
I see that there is a suspicious change [here](https://github.com/bottlepy/bottle/commit/d85a6983ceedacd9ab9afbcd027139d8773b67ac):
```python
environ['PATH_INFO'] = path.encode('latin1').decode('utf8', 'ignore')
```
Where original cause of the error was removed and replaced by `'ignore'`.
Also fixed deprecation warnings, where:
```python
@self.subapp.route('')
```
Does exactly same thing as this:
```python
@self.subapp.route('/test/<test>')
```
Where `''` is passed to `route()`, then `makelist()` utility assumes that nothing is passed and falls back to path autogeneration from callback function. Not sure if this is expected behaviour?
> Add tests for #602 bug

- bottle.py
- test/test_sendfile.py
Mutating the passed in dict can produce unexpected results if the caller re-uses the dict, e.g. uses the same set of headers for multiple files.
> Don't mutate headers dict passed into static_file()

- setup.py
- tox.ini
Bottle currently declares support for EOL versions of Python.
Also, some supported Python versions aren't properly published.
> Clean eol python versions

- docs/recipes.rst
I fixed a broken link to beaker documentation. The new link came from beaker's README.
> Fix a broken link to beaker documentation

- docs/plugins/index.rst
I made something based on bottle that allows us to auto-fill function arguments using request data.
```python
@fill_args
def some_function(json_key):
pass
some_function()
```
I'm not sure if bottle accepts these kinds of pull requests but I thought I'd give it a shot anyways. :shrug: Thanks for the amazing project.
> Add bottle tools to plugins doc page

- bottle.py
- test/test_exc.py
Recommended by pep-3333 to enable middleware to provide exception handling
services, e.g. custom exception logging.
See https://www.python.org/dev/peps/pep-3333/#error-handling
Note that the exc_info is temporarily stored in the environ to pass it up
from _handler() to wsgi(), where start_response() is called. There may be
a better way to do this, e.g. storing it in the response object.
Supersedes https://github.com/bottlepy/bottle/pull/1097, and includes the tests from @BubaVV in https://github.com/bottlepy/bottle/pull/1103
> Improve wsgi error handling 013

- bottle.py
The current improvement really helps when using multiple apps.
When I start such an application I like logging which routes are
available, for example one can do:
```
for r in main_app.routes:
print(r)
```
Which previously gave this:
```
<GET '<:re:(de|us)?\\/?>' <function index at 0x7f750fda9670>>
<GET '/<:re:(de/|us/)?>hello/<name:path>/<_id:int>/' <function _index_with_param at 0x7f750fda9700>>
<GET '/<:re:(de/|us/)?><:re:foo>/' <function _index at 0x7f750fda9820>>
<GET '/<:re:(de/|us/)?><url:path>/' <function main at 0x7f750fda9940>>
<GET '<:re:(de|us)?\\/?>' <function main at 0x7f750fda9940>>
<GET '/admin/login/' <function Auth.get_login_template at 0x7f751061e670>>
<POST '/admin/login/' <function Auth.post_login_template at 0x7f751061e700>>
<GET '/admin/' <function index at …
```
> Improve __repr__ of Route

- bottle.py
- docs/changelog.rst
- docs/development.rst
- docs/recipes.rst
Fixes some typos in documentation. The typos are in po files too. Not sure if I need to change them manually or it's done as part of build process.
> Fix typos in documentation.

- bottle.py
- test/test_environ.py
This PR fixes a bug where setting an existing, read-only property of a BaseRequest object does not raise an AttributeError.
Fixes #1359
> Fix #1359: check for attribute using hasattr

- bottle.py
- test/test_sendfile.py
Previously, if the If-Modified-Since header was an empty string it wouldn't be parsed into an int (or None), but would still be compared to the int mtime, causing a TypeError.
> Fix handling of empty If-Modified-Since header for static files

- bottle.py
CherryPy in both Debian Bookworm and Ubuntu Jammy is at version 18 and no longer provides a WSGI server. Add support for cheroot to the current bottle release to unbreak that somewhat. All commits are cherry-picks (backports) from the master branch.
> Release 0.12+cheroot

- bottle.py
so use getfullargspec on all 3.x versions instead.
With this all tests (from test/testall.py) that work on 3.10.4 also work on 3.11.0b3.
> getargspec is gone in python 3.11

- docs/deployment.rst
- docs/tutorial.rst
- docs/tutorial_app.rst
I edited the links tutorial files for cherrypy project
so they point to the right webresource cherrypy.dev
I also updated the recently updated web reference for pythonpaste, with https, 
and updated the reference where it was missing.
> updated web links for pythonpaste and cherrypy projects

- Makefile
Github action tests using pytest, so I figured it would be nice to have consistency and use pytest for local makefile call, too.
Next step:  update github actions to just call `make coverage` or `make test`?
> update makefile to use pytest instead of unittest

- bottle.py
- docs/changelog.rst
- test/test_sendfile.py
Do not instruct browsers to transparently uncompress gzipped files.
> Fix #1350: Serve compresed files as is in static_file()

- bottle.py
third arg of `getattr` is default value
> remove some redundant from FileCheckerThread.run()

- bottle.py
"%r" placeholder exists at least from 2008
https://www.python.org/dev/peps/pep-3140/
> refactor ServerAdapter.__repr__()

- bottle.py
- docs/changelog.rst
- docs/deployment.rst
- docs/tutorial.rst
- setup.py
The executable script installed into (virtual) environments was named `bottle.py`, which could result in circular imports. The old name is now deprecated (but still installed) and the new executable ist named just `bottle`.
> Deprecate bottle.py script install

- .github/workflows/run_tests.yml
Related to:
* #1438
* https://www.python.org/downloads/release/python-3130/
* https://pythoninsider.blogspot.com/2024/10/python-3130-final-released.html
* https://devguide.python.org/versions/
> Add Python 3.13 to the testing

- docs/tutorial.rst
This pull request fixes a typo in the tutorial.rst file.
* Corrected the typo from "raied" to "raised" on line 279 in the tutorial.rst file
> docs: Fix typo in tutorial.rst

- bottle.py
- docs/changelog.rst
- docs/tutorial.rst
- test/test_environ.py
- test/test_fileupload.py
- test/test_formsdict.py
- test/test_route.py
- test/test_sendfile.py
- test/test_wsgi.py
- test/tools.py
Remove (most of) Python 2 workarounds, one commit at a time.
> Drop Python 2

- bottle.py
Bottle doesn't correctly support repeated query parameters.
For example:
```python
app.get_url("page", animals=["cat", "dog"])
````
Generates:
`/page?animals=%5B%27cat%27%2C+%27dog%27%5D`
Instead of the expected and standards-compliant:
`/page?animals=cat&animals=dog`
This PR adds proper support for repeated query parameters by using `urlencode(..., doseq=True)`
> When a sequence of two-element tuples is used as the query argument, the first element of each tuple is a key and the second is a value. The value element in itself can be a sequence and in that case, if the optional parameter doseq evaluates to True, individual key=value pairs separated by '&' are generated for each element of the value sequence for the key. The order of parameters in the encoded string will match the order of …
> feat: add support for repeated query params

- test/test_config.py
- test/test_resources.py
- test/test_sendfile.py
> Close #1484: changes to make tests pass on Windows
