bottlepy/bottle

docs/index.rst
docs/plugindev.rst
docs/tutorial.rst
docs/tutorial_app.rst

It's [pretty discouraging](http://adamonishi.com/2015/02/obviously-language-in-education/) to be told you should have known something you don't know.

Don't berate users about their lack of domain-specific knowledge.

---

bottle.py
test/test_server.py
test/travis-requirements.txt

Add aiohttp 

---

.travis.yml

send notification on crash build to IRC #bottlepy

---

docs/deployment.rst

The current version of app.wsgi example fails

Add import os to app.wsgi example

---

docs/tutorial_app.rst

Fixes issue #705 
Signed-off-by: Aayush Kasurde <aayush.kasurde@gmail.com>

Remove validate decorator related documentation

---

bottle.py
test/example_settings.py
test/test_config.py

Fixes #772, Includes tests, passed.

Fixes #772

---

bottle.py
test/test_environ.py

Added 2 tests of max cookie name and length.

Test of cookie name and value length

---

Makefile
README.rst
setup.py
test/build_python.sh
test/travis-requirements.txt
test/travis_setup.sh

Removing unecessary 2.5 test dependencies
Delete some 2.5 and 3.1 things

Remove 2.5 and 3.1 things

---

docs/recipes.rst

This is a small, silly change. The spacing was 8 spaces in rather than 4.

Fix spacing in Recipe doc

---

bottle.py

By default, Python's HMAC algorithm uses MD5 (see https://docs.python.org/2/library/hmac.html) which is deemed as cryptographically broken and unsuitable for further use. This change makes SHA256 the default and also allows users to select the hashing function being used a runtime.

Import module hashlib and change default hashing algorithm of HMAC from MD5 to SHA256

---

plugins/werkzeug/README

the document of `bottle-werkzeug` is a little confused.

Typo fix on bottle-werkzeug README

---

bottle.py

Fix coding style

---

setup.py

Add PyPI classifier for Py 3.4 and 3.5

---

docs/changelog.rst

Cleaned up the spacing so that it properly renders

Update changelog.rst indentation

---

bottle.py
test/test_server.py

* added custom asyncio loop ServerAdapter
* added UVLoop server option

Add Support for UVLoop and custom asyncio loop option

---

bottle.py

For readable stacktrace from jinja2

Jinja2Template: Pass filename to Jinja2

---

bottle.py
docs/configuration.rst

Add documentation for ConfigDict.load_module

---

bottle.py

Use update_wrapper, such that the information in the wrapper is more
complete. Similar to reify in pyramid.

Tiny update to cached_property

---

.coveragerc
.travis.yml
Makefile

Enable coverage reporting and collection in coveralls.

Re enable coverage

---

bottle.py
test/test_route.py

Drop opt parser

---

bottle.py

Fix warning about using absolute template path names

---

docs/plugins/index.rst

I have made a proposal to update the list of plugins.

Proposal to update the list of plugins.

---

docs/plugins/index.rst

I have created two new plugins:
returns all errors in json format (even those generated with HTTPError)
Integrates cerberus schemas into bottle decorators

New plugins proposal

---

bottle.py

References:
- https://tools.ietf.org/html/rfc7725
- https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Status/451
This commit should make evil governments happy! 😈😈😈

Add HTTP status code 451 according to RFC 7725

---

docs/recipes.rst

unit test mocking documentation

---

docs/recipes.rst

a slightly tweaked version of @defnull's warning suggestion in #961

---

docs/_locale/_pot/changelog.pot
docs/_locale/de_DE/LC_MESSAGES/changelog.po
docs/_locale/pt_BR/LC_MESSAGES/_pot/changelog.po
docs/_locale/pt_BR/LC_MESSAGES/changelog.po
docs/_locale/ru_RU/LC_MESSAGES/changelog.po
docs/_locale/zh_CN/LC_MESSAGES/_pot/changelog.po
docs/_locale/zh_CN/LC_MESSAGES/changelog.po

Rel: https://github.com/bottlepy/bottle/issues/925

fix links commits #925

---

docs/plugins/index.rst

Let me know if you think it is at the right place.
Thank you.

Added bottle-oauthlib project reference

---

bottle.py

fix code style

---

test/test_wsgi.py

from bottle import touni

---

bottle.py

Delattr broken

---

test/test_outputfilter.py
test/test_plugins.py

Fix failed test caused by ujson

---

.circleci/config.yml
Makefile
README.rst
docs/_locale/_pot/index.pot
docs/_locale/_pot/tutorial.pot
docs/_locale/de_DE/LC_MESSAGES/index.po
docs/_locale/de_DE/LC_MESSAGES/tutorial.po
docs/_locale/pt_BR/LC_MESSAGES/index.po
docs/_locale/pt_BR/LC_MESSAGES/tutorial.po
docs/_locale/ru_RU/LC_MESSAGES/index.po
docs/_locale/ru_RU/LC_MESSAGES/tutorial.po
docs/_locale/zh_CN/LC_MESSAGES/index.po
docs/_locale/zh_CN/LC_MESSAGES/tutorial.po
docs/changelog.rst
docs/tutorial.rst
setup.py
tox.ini

Be more consistent about supporting Python 3.4 to 3.7

---

.github/workflows/run_tests.yml

Speed up testing by running all five versions of Python  in parallel.

run_tests.yml: run five tests in parallel

---

bottle.py
test/test_environ.py
test/test_sendfile.py

fix date formatting for non-English locale

---

bottle.py

Fix the Allow: header value in 405 "Method not allowed." response in the 0.12 branch

---

bottle.py

This affords a considerable saving in terms of system resources.

reuse port in Bjoern adapter

---

bottle.py

remove useless assignment

---

docs/plugins/index.rst

New plugin for adding cors-headers to all the bottle app

Adding new plugin

---

test/test_server.py

Fix syntax warning over comparison of literals using is.

---

bottle.py

refactor.WSGIFileWrapper.__iter__()

---

docs/tutorial.rst

Change capitalization to title case for consistency.

Fix title case

---

bottle.py

Fixed: #1361
See issue for context.

fix #1361 inclusive language comment

---

bottle.py

My oh my. Thank goodness I clicked this link while I was at home. It would be disastrous if I were in the office or public space.
⚠️ NSFW Warning: Please **DO NOT** go to http://www[dot]fapws[dot]org/ if you're in a public space.

Fix the link for fapws project.

---

README.rst

update README.md links

---

docs/faq.rst

Fix typo in faq.rst
